---
# tasks file for create_repo
- name: Create a bitbucket repo
  uri:
    url: http://13.126.124.176:7990/rest/api/1.0/projects/{{project_id}}/repos
    method: POST
    body: { "name": "{{repo_name}}", "scmId": "git", "forkable": false }
    body_format: json
    headers:
      "Content-Type": "application/json"
      'Authorization': 'Bearer {{auth}}'
    status_code: 201
- name: Create master branch with sample commit
  uri:
    url: http://13.126.124.176:7990/api/latest/projects/{{project_id}}/repos/{{repo_name}}/browse/README.md
    method: PUT
    body: 
      file1:
        filename: readme.md
        content: "{{role_path}}/files/readme.md"
        message: First commit
        branch: master
    body_format: raw
    headers:
      'Authorization': 'Bearer {{auth}}'
    status_code: 
    - 201
    - 200

