---
# tasks file for create_repo
- name: Create a bitbucket repo
  uri:
    url: http://13.126.124.176:7990/rest/api/1.0/projects/{{project_id}}/repos
    method: POST
    body: { "name": "{{repo_name}}", "scmId": "git", "forkable": false }
    body_format: json
    headers:
      "Content-Type": "application/json"
      'Authorization': 'Bearer {{auth}}'
    status_code: 201
- name: Create master branch with sample commit
  command: " curl -X PUT \
 --header 'Authorization: Bearer {{auth}}' \
 -F content=@{{role_path}}/files/readme.md \
 -F 'message=Master commit' \
 -F branch=master \
  http://13.126.124.176:7990/rest/api/latest/projects/{{project_id}}/repos/{{repo_name}}/browse/README.md "

- name: Create Develop branch from Master branch
  uri:
    url: http://13.126.124.176:7990/rest/api/1.0/projects/{{project_id}}/repos/{{repo_name}}/branches
    method: POST
    body: {"name": "develop", "startPoint": "refs/heads/master"}
    body_format: json
    headers:
      'Content-Type': 'application/json'
      'Authorization': 'Bearer {{auth}}'
    status_code:
     - 201
     - 200
